// <auto-generated />
namespace com.boutique.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_parameter_types : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_parameter_types));
        
        string IMigrationMetadata.Id
        {
            get { return "201602170821376_update_parameter_types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
