//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.boutique.GlobalResource.WebService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebServiceEndPoints {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebServiceEndPoints() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.boutique.GlobalResource.WebService.WebServiceEndPoints", typeof(WebServiceEndPoints).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/audios/{0}/proxy/raw?__sessionKey={1}.
        /// </summary>
        public static string AudioStream {
            get {
                return ResourceManager.GetString("AudioStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security/users/password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search/saved.
        /// </summary>
        public static string DeleteSavedFilter {
            get {
                return ResourceManager.GetString("DeleteSavedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filesystem/assetFilePaths.
        /// </summary>
        public static string FileSystemAssetFilePaths {
            get {
                return ResourceManager.GetString("FileSystemAssetFilePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filesystem/vfs?path=.
        /// </summary>
        public static string GetFileDirectory {
            get {
                return ResourceManager.GetString("GetFileDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata/groups/{0}/properties.
        /// </summary>
        public static string GetGroupProperties {
            get {
                return ResourceManager.GetString("GetGroupProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata/groups?assetId={0}&amp;assetType={1}.
        /// </summary>
        public static string GetGroups {
            get {
                return ResourceManager.GetString("GetGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to categories/.
        /// </summary>
        public static string GetIngestCategories {
            get {
                return ResourceManager.GetString("GetIngestCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/file/scratch/uniqueDirectory?endpoint=windows.
        /// </summary>
        public static string GetIngestFilePath {
            get {
                return ResourceManager.GetString("GetIngestFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingest-forms.
        /// </summary>
        public static string GetIngestForms {
            get {
                return ResourceManager.GetString("GetIngestForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/meta/lookup/{0}.
        /// </summary>
        public static string GetIngestWorkFlowLookUpListItems {
            get {
                return ResourceManager.GetString("GetIngestWorkFlowLookUpListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/meta/picklist/{0}.
        /// </summary>
        public static string GetIngestWorkFlowPickListItems {
            get {
                return ResourceManager.GetString("GetIngestWorkFlowPickListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/metadata/prelude/schema.json.
        /// </summary>
        public static string GetSchemaJson {
            get {
                return ResourceManager.GetString("GetSchemaJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1/system/config/{0}.
        /// </summary>
        public static string GetServerProperty {
            get {
                return ResourceManager.GetString("GetServerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/{0}/{1}.
        /// </summary>
        public static string GetSingleAsset {
            get {
                return ResourceManager.GetString("GetSingleAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/{0}/{1}/metadata.
        /// </summary>
        public static string GetSingleAssetMetadata {
            get {
                return ResourceManager.GetString("GetSingleAssetMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows/executions/{0}.
        /// </summary>
        public static string GetWorkFlowExecution {
            get {
                return ResourceManager.GetString("GetWorkFlowExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows?fetchLimit=100&amp;includeArchived=false&amp;includeDisabled=false&amp;includeGlobal=true&amp;userCanExecuteOnly=true.
        /// </summary>
        public static string GlobalWorkFlow {
            get {
                return ResourceManager.GetString("GlobalWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/images/{0}/proxy/raw?__sessionKey={1}.
        /// </summary>
        public static string ImageStream {
            get {
                return ResourceManager.GetString("ImageStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingest-forms/{0}/metadata-properties?limit=1000&amp;offset=0.
        /// </summary>
        public static string IngestFormMetadataProperties {
            get {
                return ResourceManager.GetString("IngestFormMetadataProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/search.
        /// </summary>
        public static string InventorySearch {
            get {
                return ResourceManager.GetString("InventorySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security/users/login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to security/users/logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata/groups/{0}/properties.
        /// </summary>
        public static string MetadataGroupProperties {
            get {
                return ResourceManager.GetString("MetadataGroupProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata/properties.
        /// </summary>
        public static string MetaDataPropertiesAll {
            get {
                return ResourceManager.GetString("MetaDataPropertiesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search/saved/version/{0}.
        /// </summary>
        public static string SavedFilters {
            get {
                return ResourceManager.GetString("SavedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search/saved.
        /// </summary>
        public static string SaveSearchFilters {
            get {
                return ResourceManager.GetString("SaveSearchFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user/preferences/{0}.
        /// </summary>
        public static string SelectedPreferences {
            get {
                return ResourceManager.GetString("SelectedPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows/{0}/start.
        /// </summary>
        public static string StartWorkFlow {
            get {
                return ResourceManager.GetString("StartWorkFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/collections/.
        /// </summary>
        public static string TaskCreateNewCollection {
            get {
                return ResourceManager.GetString("TaskCreateNewCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inventory/videos/{0}/secureStreamingUrl.
        /// </summary>
        public static string VideoClipStream {
            get {
                return ResourceManager.GetString("VideoClipStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows/{0}/params.
        /// </summary>
        public static string WorkflowDynamicProperties {
            get {
                return ResourceManager.GetString("WorkflowDynamicProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows/executions.
        /// </summary>
        public static string WorkflowExecutions {
            get {
                return ResourceManager.GetString("WorkflowExecutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows/{0}/picklistoptions/{1}.
        /// </summary>
        public static string WorkFlowHasPickListTrue {
            get {
                return ResourceManager.GetString("WorkFlowHasPickListTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows?fetchLimit=10000&amp;userCanExecuteOnly=false&amp;includeDisabled=false&amp;includeArchived=false&amp;includeGlobal=true.
        /// </summary>
        public static string WorkFlowItems {
            get {
                return ResourceManager.GetString("WorkFlowItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to workflows?fetchLimit=100&amp;includeArchived=false&amp;includeDisabled=false&amp;includeGlobal=false&amp;{0}&amp;userCanExecuteOnly=true.
        /// </summary>
        public static string WorkflowMediaItem {
            get {
                return ResourceManager.GetString("WorkflowMediaItem", resourceCulture);
            }
        }
    }
}
