//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.boutique.GlobalResource.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NamedValue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NamedValue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.boutique.GlobalResource.Strings.NamedValue", typeof(NamedValue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string HttpDeleteMethod {
            get {
                return ResourceManager.GetString("HttpDeleteMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET.
        /// </summary>
        public static string HttpGetMethod {
            get {
                return ResourceManager.GetString("HttpGetMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POST.
        /// </summary>
        public static string HttpPostMethod {
            get {
                return ResourceManager.GetString("HttpPostMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PUT.
        /// </summary>
        public static string HttpPutMethod {
            get {
                return ResourceManager.GetString("HttpPutMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/json.
        /// </summary>
        public static string HttpWebRequestContentType {
            get {
                return ResourceManager.GetString("HttpWebRequestContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        public static string HttpWebRequestContentTypePlain {
            get {
                return ResourceManager.GetString("HttpWebRequestContentTypePlain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio.
        /// </summary>
        public static string TypeAudio {
            get {
                return ResourceManager.GetString("TypeAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clip.
        /// </summary>
        public static string TypeClip {
            get {
                return ResourceManager.GetString("TypeClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collection.
        /// </summary>
        public static string TypeCollection {
            get {
                return ResourceManager.GetString("TypeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        public static string TypeDocument {
            get {
                return ResourceManager.GetString("TypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        public static string TypeImage {
            get {
                return ResourceManager.GetString("TypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unclassified.
        /// </summary>
        public static string TypeUnclassified {
            get {
                return ResourceManager.GetString("TypeUnclassified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video.
        /// </summary>
        public static string TypeVideo {
            get {
                return ResourceManager.GetString("TypeVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1}/{2}.
        /// </summary>
        public static string WebServiceURLFormat {
            get {
                return ResourceManager.GetString("WebServiceURLFormat", resourceCulture);
            }
        }
    }
}
